# Generated by Django 5.0.1 on 2024-08-05 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('words', '0002_alter_words_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='categories.categories'),
        ),
    ]
